### PR TITLE
Bugfix:

### PR DESCRIPTION
**Pull request by mrmk85**
parse existing files with an addition space.
Issue during S17F1 <-> S17F10

### CODE REVIEW

**Comment by rikogercke** [comment]
First of all, thanks for your contribution.
Can you tell me whats different in S17? Will it continue to work as before with the other episodes? Last time I used it, I had no problems.

**Comment by mrmk85** [comment]
I don't know whats different in S17.
I had the problem that the script skips always S17F1 during downloading.
If I don't want to download all and all over again I use your skipping option in main.py and I got the same issue in S17F1.
It was always identify as S17F10 so I mod the search pattern and than it works.

**Comment by rikogercke** [comment]
I gues I know what's happening. S17E10 contains the string "S17E1". But I wonder why it worked when I used it the last time. I'm going to look at my dataset tomorrow.

**Comment by mrmk85** [comment]
I wonder that it only happens on S17E10 <-> S17E1 AND S16E10 <-> S16E1.
All other works fine, S18E10 <-> S18E1 and so on

**Comment by rikogercke** [comment]
Is there any kind of log or error that you could hand me or is it just doing it without throwing informations?

**Comment by rikogercke** [comment]
S15 -> S1 is okay too?

**Comment by Oberfail** [comment]
I just ran into the same issue. All E1 of each season were skipped in the downloads. Applying this Bugfix solved the issue and downloaded the Episodes it first skipped.

**Pull request merged**
